INSERT INTO Grupy (rok,grupa) VALUES ('1inf-inz','a');
INSERT INTO Grupy (rok,grupa) VALUES ('1inf-inz','a');
INSERT INTO Grupy (rok,grupa) VALUES ('1inf-inz','b');
INSERT INTO Grupy (rok,grupa) VALUES ('1inf-inz','c');
INSERT INTO Grupy (rok,grupa) VALUES ('1inf-inz','d');
INSERT INTO Grupy (rok,grupa) VALUES ('2inf-inz','a');
INSERT INTO Grupy (rok,grupa) VALUES ('2inf-inz','a');
INSERT INTO Grupy (rok,grupa) VALUES ('2inf-inz','b');
INSERT INTO Grupy (rok,grupa) VALUES ('3inf-lic','a');