/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>

pliczek *
start_1_svc(polacz *argp, struct svc_req *rqstp)
{
	static pliczek  result;
	result.pusty = 0;
	if(argp->tryb == 0)
		result.plik = open(argp->nazwa, O_RDONLY);
    if(argp->tryb == 1)
        result.plik = open(argp->nazwa, O_WRONLY | O_TRUNC);
	if(argp->tryb == 2){
        result.plik = open(argp->nazwa, O_RDONLY);
		return &result;
	}
	if(result.plik < 0){
		result.plik = creat(argp->nazwa, 0666);
		result.pusty = 1;
	}
	return &result;
}

zwroc *
pull_1_svc(pobieranie *argp, struct svc_req *rqstp)
{
	static zwroc  result;
	if(argp->przesun != 0){
		if((result.ilosc = lseek(argp->plik, argp->przesun, SEEK_CUR)) < 0){
			return &result;
		}
	}
	result.ilosc = read(argp->plik, result.dane, 2048);
	return &result;
}

int *
push_1_svc(wyslij *argp, struct svc_req *rqstp)
{
	static int  result;
	result = write(argp->plik, argp->dane, strlen(argp->dane));
	return &result;
}

int *
koniec_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = close(*argp);
	return &result;
}
