/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"

bool_t
xdr_pliczek (XDR *xdrs, pliczek *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->plik))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pusty))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_polacz (XDR *xdrs, polacz *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->tryb))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nazwa, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pobieranie (XDR *xdrs, pobieranie *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->plik))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pozycja))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->przesun))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_zwroc (XDR *xdrs, zwroc *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->ilosc))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->dane, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_wyslij (XDR *xdrs, wyslij *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->plik))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->dane, 2048,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
